#!/bin/bash

subset="TIME_MEASUREMENT FIFO_1 RR_3 SJF_4"

for f in $subset; do
    dmesg --clear
    echo "$f"
    command time -f %E sh -c "./program < test/\"$f\".txt > demo/\"$f\"_output.txt"
    dmesg | grep "Project1" | tee demo/"$f"_dmesg.txt
done
